### ISSUE TITLE
Add image metadata to the OpenStack node-images.yaml as is defined in the related SCS standard

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/cluster-stacks#23]
/kind feature

SCS stadard [scs-0102-v1-image-metadata](
https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0102-v1-image-metadata.md) describes what metadata (properties and tags) should be assigned to the image that is offered by the CSP.

These properties and tags are then evaluated by the Conformance Tests (script image-md-check.py).

CSPO supports a full list of create options, defined by the OpenStack API. Hence the `node-images.yaml ` should include mandatory  
properties and tags for each image. 

### Current state of node-images.yaml (openstack cluster stack)

```
apiVersion: openstack.infrastructure.clusterstack.x-k8s.io/v1alpha1
openStackNodeImages:
  - url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.28/ubuntu-2204-kube-v1.28.6.qcow2
    createOpts:
      name: ubuntu-capi-image-v1.28.6
      disk_format: qcow2
      container_format: bare
      visibility: shared
```

### Desired state  of node-images.yaml (openstack cluster stack)

```
apiVersion: openstack.infrastructure.clusterstack.x-k8s.io/v1alpha1
openStackNodeImages:
  - url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.28/ubuntu-2204-kube-v1.28.6.qcow2
    createOpts:
      name: ubuntu-capi-image-v1.28.6
      disk_format: qcow2
      container_format: bare
      visibility: shared
      properties:
      - architecture: x86_64 
      - ....
      tags:
      - managed_by_scs
```

Note: see [KaaS V1 implementation](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/bin/upload_capi_image.sh#L51)
